### ISSUE TITLE
go make issue

### ISSUE THREAD

**Issue by dokyun-kim** [newrelic/nri-network-telemetry#5]
Hello,
I'm having the following issue.

$ go version
go version go1.13.7 linux/amd64
$ pwd
/home/centos/go/src/github.com/newrelic/nri-network-telemetry
$ make
![image](https://user-images.githubusercontent.com/59544391/73822959-9bf43f80-483a-11ea-8059-1063c757fd89.png)

Please tell me how to make.

Thank you

**Comment by jthurman42** [comment]
This should now be resolved.
