### ISSUE TITLE
Make will not compile binaries and fails at misspell [spell-check]

### ISSUE THREAD

**Issue by kimnjeru** [newrelic/nri-network-telemetry#9]
### Description
During the build phase of the integration running `make` fails consistently on Ubuntu and Linux resulting in no compiled binaries
 
### Go Version

Ubuntu: go version go1.14.4 linux/amd64
Linux:  go version go1.13.4 linux/amd64

### Current behavior
Binary compile fails and emits error during the spell-check portion.

```
[ec2-user@ip-10-0-0-25 nri-network-telemetry]$ make
=== nri-network-telemetry === [ git-hooks        ]: Configuring git hooks...
=== nri-network-telemetry === [ cover-clean      ]: removing coverage files...
=== nri-network-telemetry === [ compile-clean    ]: removing binaries...
=== nri-network-telemetry === [ release-clean    ]: distribution files...
=== nri-network-telemetry === [ tools            ]: Installing tools required by the project...
=== nri-network-telemetry === [ deps             ]: Installing package dependencies required by the project...
=== nri-network-telemetry === [ spell-check      ]: Checking for spelling mistakes with misspell...
make: misspell: Command not found
make: *** [spell-check] Error 127
[ec2-user@ip-10-0-0-25 nri-network-telemetry]$ go version
go version go1.13.4 linux/amd64
```

### Expected behavior
Binaries should compile and complete cleanly resulting in binaries in ./bin directory

### Steps To Reproduce
1. git clone https://github.com/newrelic/nri-network-telemetry.git
2. cd nri-network-telemetry
3. make

### Debug Output (if applicable)
n/a

### Additional Context
n/a

### References or Related Issues
None that I am aware of

**Comment by zlesnr** [comment]
Hi, thank you for reporting the issue.  As a work around, try running `make compile-only` to get just the binary to build.  Alternatively, it looks like the `misspell` command is missing, so if you are able to install that package, it could help move past that step.

**Comment by kimnjeru** [comment]
Thanks.  I was able to get past this by setting `GOPATH` and adding `GOPATH/bin` to `PATH` and then rerunning `make`.

**Comment by jthurman42** [comment]
nri-network-telemetry installx misspell automatically, as it's a tools dependency.  You are correct that `$GOPATH/bin` does need to be in your `$PATH` for that to work correctly.
